print('Welcome to the Mad Lib Generator!')

adjective1 = raw_input('Type in an adjective: ')
adjective2 = raw_input('Another adjective:')
adjective3 =  raw_input('And another adjective:')
adjective4 = raw_input('One more adjective:')
plural_animal = raw_input('Plural animal (e.g., puppies):')
verb = raw_input('Now a verb:')
plural_noun = raw_input('Now a plural noun:')
woman_musician = raw_input('The first name of a woman musician:')
beverage = raw_input('A beverage:')
plural_body_part = raw_input('And finally, a plural body part:')



print('')
print('Excellent choices! Here is your story...')
print('-----------------------------------------------------')
print("There once was a " + str(adjective1) + " programmer named " + str(woman_musician) + ' who')
print("wanted to build a " + str(adjective2) + " mobile app to help " + str(adjective3) + " " + str(plural_animal) + " find new homes.")
print("")
print(str(woman_musician) + ' stayed up all night, drinking lots of caffeinated ' + str(beverage))
print('as she worked and worked, trying to complete her ' + str(adjective4) + ' program.')
print('')
print('Whenever ' + str(woman_musician) + ' hit a dead end, she would exclaim ' + str(plural_noun) + '!')
print('But she was not discouraged, and after a quick break to ' + str(verb) + ' and clear her head,')
print('she got back to work.')
print('')
print('By morning, when the sun started to rise, she let out a big yawn and')
print('stretched her ' + plural_body_part  + '. Finally, she was done.')
print('--------------------------------------------------------------------')
